### ISSUE TITLE
Website example doesn't work in Firefox

### ISSUE THREAD

**Issue by green3g** [bitovi/incremental#43]
Just tried running the example in Firefox. When it did work, the client app was much faster than Velocirender (odd). In chrome it worked just fine. Often though I couldn't get the example to work in firefox and ended up with:

![image](https://user-images.githubusercontent.com/5471079/52231912-b5a62400-2880-11e9-828a-a2200276e34d.png)

Firefox V 65 on Windows 7x64

**Comment by matthewp** [comment]
Yeah, I'm investigating this. Thanks for filing an issue though.
